"""Add prep_session_id to Answer table

Revision ID: 25543b60e61a
Revises: 
Create Date: 2024-06-30 08:52:11.266448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25543b60e61a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prep_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('quiz_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'],  'fk_prep_session_quiz_id', ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'],   'fk_prep_session_user',),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('prep_session_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'prep_session', ['prep_session_id'], ['id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prep_session_id')
        batch_op.drop_column('question_id')

    op.drop_table('prep_session')
    # ### end Alembic commands ###
