"""Add language and type to Quiz model

Revision ID: 61034b0e4a83
Revises: 84d7c47e9a55
Create Date: 2024-07-28 19:27:00.169445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61034b0e4a83'
down_revision = '84d7c47e9a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###
    # Set default values for existing rows
    op.execute("UPDATE quiz SET type = 'QUESTIONS' WHERE type IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
