"""Rename language to lng in Quiz and add lng to PrepSession

Revision ID: f20ab8d26aaa
Revises: 61034b0e4a83
Create Date: 2024-08-03 17:43:53.710766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20ab8d26aaa'
down_revision = '61034b0e4a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               nullable=False)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('language', new_column_name='lng', existing_type=sa.String(length=50))

    # Update existing rows in quiz table to set lng = 'en'
    op.execute("UPDATE quiz SET lng = 'en' ")

    # Add 'lng' column to prep_session table
    with op.batch_alter_table('prep_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               nullable=True)


    with op.batch_alter_table('prep_session', schema=None) as batch_op:
        batch_op.drop_column('lng')

        # Rename 'lng' back to 'language' in quiz table
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('lng', new_column_name='language', existing_type=sa.String(length=50))
    # ### end Alembic commands ###
