"""Add target_lng to Quiz model

Revision ID: f5053bd3f311
Revises: e3525a43694c
Create Date: 2024-08-17 14:58:54.490229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5053bd3f311'
down_revision = 'e3525a43694c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_lng', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('target_lng')

    # ### end Alembic commands ###
